{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "loadshaper.fullname" . }}
  labels:
    {{- include "loadshaper.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "loadshaper.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.networkPolicy.ingress }}
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
    {{- else }}
    # Allow iperf traffic for network load generation between loadshaper instances
    - from:
        - podSelector:
            matchLabels:
              {{- include "loadshaper.selectorLabels" . | nindent 14 }}
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              {{- include "loadshaper.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.config.NET_PORT }}
    # Allow Prometheus scraping if ServiceMonitor is enabled
    {{- if .Values.serviceMonitor.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.serviceMonitor.namespace | default "monitoring" }}
      ports:
        - protocol: TCP
          port: {{ .Values.serviceMonitor.port | default 8080 }}
    {{- end }}
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.egress }}
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
    {{- else }}
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow iperf traffic for network load generation between loadshaper instances
    - to:
        - podSelector:
            matchLabels:
              {{- include "loadshaper.selectorLabels" . | nindent 14 }}
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              {{- include "loadshaper.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.config.NET_PORT }}
    # Allow external internet traffic for Oracle Cloud threshold compliance (restricted to known endpoints)
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: iperf-server
        # Allow communication with well-known internet load testing endpoints
        - podSelector: {}
          namespaceSelector:
            matchLabels:
              name: load-testing
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: UDP
          port: 80
        - protocol: UDP
          port: 443
    {{- end }}
{{- end }}